.Dd $Mdocdate$
.Dt RMTMP 1
.Os
.Sh NAME
.Nm rmtmp
.Nd remove temporary files
.Sh SYNOPSIS
.Nm
.Op .Fl d .Ar tmpdir
.Op Fl v
.Ar prefix
.Sh DESCRIPTION
.Nm
steps through the directory entry for 
.Pa /tmp .
When it finds a regular file, it checks to see if it starts with the prefix
passed in; if so, that file is removed.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d Ar tmpdir
Specify the temporary directory. The default value is "/tmp".
.It Fl v
Select verbose mode. In verbose mode, every 1000 files,
.Nm
prints the current number of files removed.
.El
.\" .Sh RETURN VALUES
.\" For sections 2, 3, & 9 only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, & 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, & 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, & 8 only.
.\" .Sh ERRORS
.\" For sections 2, 3, & 9 only.
.\" .Sh SEE ALSO
.Sh STANDARDS
.Nm
conforms to ANSI C and the SUSv4.
.\" .Sh HISTORY
.Sh AUTHORS
.Nm
was written by
.An Kyle Isom Aq Mt kyle@tyrfingr.is .
\.".Sh CAVEATS
.Sh BUGS
Please report all bugs to the author.

